### ISSUE TITLE
Autoprefixer support?

### ISSUE THREAD

**Issue by dehghani-mehdi** [xoofx/SharpScss#10]
Hello,

Is there any plan to support autoprefixer?

**Comment by xoofx** [comment]
> Is there any plan to support autoprefixer?

Don't know anything about this. SharpScss is exposing what libsass is exposing. Is it part of libsass?

**Comment by Taritsyn** [comment]
> Is it part of libsass?

Hello, Alexandre!

No. This is a [separate product](https://github.com/postcss/autoprefixer) not related to Sass. Written in JavaScript and mostly used in conjunction with Node.js, but there is also a [browser version](https://github.com/ai/autoprefixer-rails).

**Comment by xoofx** [comment]
> No. This is a separate product not related to Sass.

Good, so I can close this issue then 😉

**Comment by dehghani-mehdi** [comment]
So problem solved without me :p

@Taritsyn I could not find any browser usage mention on [autoprefixer-rails](https://github.com/ai/autoprefixer-rails), would you show me what you mean by ` browser version` here?

Update

Never mind, I figure it out ;)
