### ISSUE TITLE
Cache problem in Compile file mode

### ISSUE THREAD

**Issue by dehghani-mehdi** [xoofx/SharpScss#11]
Hi,

I have to `.scss` files, using `FileSystemWatcher` I detect the file changes and re-comple scss using SharpScss using thread (inside async method). doesn't matter which file changed, I always get first file content as compiled css.

BTW it happens only in Compile file mode.

Seems like SharpScss doesn't work well when use inside async method (_I didn't test outside of async method_). I did the same with [LibSassHost](https://github.com/Taritsyn/LibSassHost) and it works fine.

Cheers!

**Comment by leotohill** [comment]
I think that I identified the cause of this problem and a workaround.  In my case, it's unrelated to asynch.  See https://github.com/xoofx/SharpScss/issues/20
