### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'libsass' or one of its dependencies: Access is denied.

### ISSUE THREAD

**Issue by Aequitatis** [xoofx/SharpScss#12]
Hello and thank you for the library and your attention.

Asp.net Core 2.1, local IIS.  Upon calling SharpScss.Scss.ConvertToCss I receive the following error in my web project however **not in my integration tests**:

`DllNotFoundException: Unable to load DLL 'libsass' or one of its dependencies: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
SharpScss.LibSass.sass_alloc_memory(size_t size)
SharpScss.LibSass+StringUtf8.op_Implicit(string text)
SharpScss.Scss.FromCore(string fromStringOrFile, bool fromFile, ScssOptions options)
Tales.Web.ComponentBundler.Scss.SharpScssCompiler.Compile(string filePath, string scss) in SharpScssCompiler.cs`
=> Last line is my code and further below is as well.

Upon inspecting the Event Viewer, I see the log item:
`The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{D63B10C5-BB46-4990-A94F-E40B9D520160}
 and APPID 
{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}
 to the user xxxx SID (xxxx) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.`

Please let me know what I'm missing or if this is a bug for my platform.

Thanks very much!

**Comment by xoofx** [comment]
> DllNotFoundException: Unable to load DLL 'libsass' or one of its dependencies: Access is denied. 

I don't know. Is the DLL actually deployed with your app? Or maybe they are not allowed by default on your setup? (IIS case?)
