### ISSUE TITLE
How to instruct the library to resolve embedded files?

### ISSUE THREAD

**Issue by xperiandri** [xoofx/SharpScss#16]
I try to compile `app.scss`
``` SCSS
@import "settings";
@import "sections";

```

And got the error
```
SharpScss.ScssException: 'Error: File to import not found or unreadable: settings.
        on line 1:1 of stdin
>> @import "settings";
   ^
'
```

All the files are embedded and gathered by `EmbeddedFileProvider`

**Comment by xperiandri** [comment]
Got it, the issue is here
https://github.com/ligershark/WebOptimizer.Sass/blob/ba05b00a2cf0702271a049c1c1bb83bc389624ce/src/Compiler.cs#L66
`TryImport` is not copied

**Comment by xoofx** [comment]
> Got it, the issue is here
> https://github.com/ligershark/WebOptimizer.Sass/blob/ba05b00a2cf0702271a049c1c1bb83bc389624ce/src/Compiler.cs#L66
TryImport is not copied

So that's probably not SharpScss related, closing then. 😉
