### ISSUE TITLE
min and max functions cause error

### ISSUE THREAD

**Issue by xperiandri** [xoofx/SharpScss#17]
```
Error: "env(safe-area-inset-right)" is not a number for `max'
        on line 1:6916 of https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css, in function `max`
        from line 1:6916 of https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
        from line 16:9 of settings
        from line 1:9 of stdin
>> :max(0px)){.fancybox-caption{padding:75px max(44px,env(safe-area-inset-right
   ------------------------------------------^
```

**Comment by xoofx** [comment]
The error is not in max but on `env(safe-area-inset-right)`

SharpScss is reporting what libsass is reporting, so this is not a problem with SharpScss.
I can't tell from this error if you are doing something wrong with the setup or that libsass is failing, but we can't do anything in SharpScss.

**Comment by xperiandri** [comment]
I've found a workaround
``` SCSS
@function max($numbers...) { @return m#{a}x(#{$numbers}); }
@function min($numbers...) { @return m#{i}n(#{$numbers}); }
```
on FancyBox repository.
It is an old SassLib that does not support new `min` and `max`

**Comment by xperiandri** [comment]
https://github.com/fancyapps/fancybox/issues/2182#issuecomment-467324022
https://github.com/sass/sass/issues/2378
