### ISSUE TITLE
Documentation: Deployment to Debian x64 requires DLL map

### ISSUE THREAD

**Issue by craigfowler** [xoofx/SharpScss#5]
I have just successfully made use of this on a Debian Linux "Jessie" x64 machine, using the `v1.3.4` NuGet package.

One alteration was required to my dev environment (and I imagine will also be needed on prod too).  That was to add a DLL map for kernel32 as such.  This was done in `/etc/mono/config`, where a number of native DLLs which are present on Windows but not Linux-based systems are re-mapped to equivalents.

The code added was:

```xml
<dllmap dll="i:kernel32">
  <dllentry dll="libdl.so" name="LoadLibrary" target="dlopen"/>
</dllmap>
```

This probably isn't an exact like-for-like, and I am probably abusing DLL maps by doing so.  Since I'm only running SharpScss as part of a build script (so the process is short-lived) I'm willing to handwave any possible memory leaks or improper resource-disposal that I might be incurring.

You may or may not wish to try any of this out and add it to your docs.

The symptom which a developer will see if the above is NOT added is a `TypeLoadException` in `LibSass`, stating that it can't load `kernel32`.

**Comment by craigfowler** [comment]
And (in researching a little further) I've discovered that I totally don't need to put this in my machine-wide config, it can go in `~/.mono/config` as well.

According to Mono documentation it should be possible to put it in my `App.config`  too, but that hasn't worked out for me.  At least - when running NUnit over my project, it's ignoring the `MyAssemblyName.dll.config` that I provided - it only respects the DLL mapping if it's in my home directory config file.

**Comment by xoofx** [comment]
SharpScss is mainly targeting `netcoreapp`. I haven't actually tried it with plain .NET/mono, but it looks like its is grabbing the 4.5 assembly which is supposed to be working mainly on Windows (hence why there is this kernel32 used). Gonna check if I can remove this... (which was used only for allowing x86/x64 native dll loading transparent...)

**Comment by xoofx** [comment]
I pushed a new version `1.3.5` that is removing the LoadLibrary code. Instead now, a single runtime DLL is copied at built time. For a `netcoreapp` this is done automatically. For a desktop app (net20-net40+), it is based on a variable in your `csproj` `SharpScssRuntime`. This is explained in the [readme of the project at section runtime](https://github.com/xoofx/SharpScss#runtime)
So you should no longer have to dllmap.

But I can't tell if/how the runtime is going to work with Mono on a non Windows machine, as the only supported runtime scenarios are `ubuntu.14.04-x64` and `osx.10.10-x64`. In your case, on a debian linux x64, you would have to specify `<SharpScssRuntime>ubuntu.14.04-x64</SharpScssRuntime>`  in your csproj, but again, can't give any guarantee that it will work. Let me know!

**Comment by craigfowler** [comment]
Thanks for the quick response.

I'm away this weekend (chasing DJs around continental Europe) but I'll be back on Tuesday and I can have another play with it then.

**Comment by craigfowler** [comment]
Cool.  Couple of updates:

I've tried updating to the latest version and it mostly works out of the box EXCEPT:

XBuild (MSBuild equivalent) on Mono isn't particularly happy with `%(Filename)%(Extension)` in the `.targets` file.  I had a feeling that the syntax I'd been using previously in a similar scenario was using the `@` symbol instead of `%` so on a hunch I tried that and it worked.  Also, MSBuild on Windows (AppVeyor at least) doesn't complain about that substitution either.

Whilst testing on Windows/AppVeyor, I tripped over an issue in which you might be interested, particularly because I probably won't be the first person to try this.  I integrated SharpScss into my build process via MSBuild as a new `Task` which kicks off the conversion process of all of the files found in a directory structure.

Interestingly, AppVeyor use 64 bit hosts for CI builds, but the 32-bit version of MSBuild.  On a Windows environment I'm not sure if this is a common occurrence or if AV are just being unusual in this regard.

It means that when building for 64-bit targets using 32-bit MSBuild, if the SharpScss binary is being selected in that same build, and you have a build task which uses SharpScss, then you end up with a crash in your build.  In short the 32-bit MSBuild tries to make use of a 64-bit `sharpscss.dll`.  The effect looks something like:

```
"C:\projects\agiil\Agiil.sln" (default target) (1) ->
"C:\projects\agiil\Agiil.Web\Agiil.Web.csproj" (default target) (2) ->
(AfterBuild target) -> 
  C:\projects\agiil\Agiil.Web\Agiil.Web.csproj(344,5): error MSB4018: The "CompileScssFiles" task failed unexpectedly.
C:\projects\agiil\Agiil.Web\Agiil.Web.csproj(344,5): error MSB4018: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
C:\projects\agiil\Agiil.Web\Agiil.Web.csproj(344,5): error MSB4018:    at SharpScss.LibSass.sass_alloc_memory(size_t size)
C:\projects\agiil\Agiil.Web\Agiil.Web.csproj(344,5): error MSB4018:    at SharpScss.LibSass.StringUtf8.op_Implicit(String text)
C:\projects\agiil\Agiil.Web\Agiil.Web.csproj(344,5): error MSB4018:    at SharpScss.Scss.FromCore(String fromStringOrFile, Boolean fromFile, ScssOptions options)
C:\projects\agiil\Agiil.Web\Agiil.Web.csproj(344,5): error MSB4018:    at SharpScss.Scss.ConvertFileToCss(String scssFile, ScssOptions options)
C:\projects\agiil\Agiil.Web\Agiil.Web.csproj(344,5): error MSB4018:    at Agiil.Web.Sass.SharpScssConverter.Convert(String inputPath, String outputPath, ScssOptions options) in C:\projects\agiil\Tools\Agiil.Web.Sass\SharpScssConverter.cs:line 13
C:\projects\agiil\Agiil.Web\Agiil.Web.csproj(344,5): error MSB4018:    at Agiil.Web.Sass.SassCompiler.Compile(FileInfo file, DirectoryInfo outputDirectory) in C:\projects\agiil\Tools\Agiil.Web.Sass\SassCompiler.cs:line 51
C:\projects\agiil\Agiil.Web\Agiil.Web.csproj(344,5): error MSB4018:    at Agiil.Web.Sass.SassCompiler.Compile(SassCompilationOptions options) in C:\projects\agiil\Tools\Agiil.Web.Sass\SassCompiler.cs:line 27
C:\projects\agiil\Agiil.Web\Agiil.Web.csproj(344,5): error MSB4018:    at Agiil.Build.Tasks.CompileScssFiles.Execute() in C:\projects\agiil\Tools\Agiil.Build.Tasks\CompileScssFiles.cs:line 27
C:\projects\agiil\Agiil.Web\Agiil.Web.csproj(344,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
C:\projects\agiil\Agiil.Web\Agiil.Web.csproj(344,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

The code which matches that error [is available here](https://github.com/csf-dev/agiil/tree/f8468c70c31ea96356b3a5a554b9ce8110a34555/Tools/Agiil.Web.Sass) btw in case you want to see it for yourself (I've since worked around it in master of that same project).

I've worked around that now by forcing AV's CI to build for x86 and not x64.  However, it might mean you want to reconsider whether to statically choose the supported architecture at build-time, or go back to auto-detecting and loading at run-time.  Whilst it means doing assembly mapping on Mono, it's a known and supported thing there.

The alternative of course is that I (and anyone else who wants SharpScss in their MSBuild sequence) build their SASS project as an `exe` rather than a `dll`.  Then, in the appropriate build target, invoke it as a new process rather than integrated into the MSBuild process.  Then it will be a 64-bit process using 64-bit libs and everything will be happy.

So, whatever you decide it's not the end of the world.  Just thought you might want to know.

**Comment by xoofx** [comment]
> XBuild (MSBuild equivalent) on Mono isn't particularly happy with %(Filename)%(Extension) in the .targets file. I had a feeling that the syntax I'd been using previously in a similar scenario was using the @ symbol instead of % so on a hunch I tried that and it worked. Also, MSBuild on Windows (AppVeyor at least) doesn't complain about that substitution either.

The syntax in SharpScss.targets is a valid msbuild syntax... The syntax using `@` aka as Transforms is mainly used when you have to work on a specific named ItemGroup (e.g `Content`...etc.), but here, we are already inside an item group (Content Include), and we have access to all the metadata of this item (`%(FileName)`)... that's unfortunate that it is not supported by XBuild... will have to check how to workaround this properly...

Concerning the x86/x64 `BadImageFormatException` indeed, this is the downside of any pinvoke wrapper, the caller needs to ensure the runtime coherency (and sometimes, as you have found, a chain of dependency can give tricky behavior...). Not sure I can do anything about this, apart from documenting it in the readme, which I forgot...
