### ISSUE TITLE
libsass not resolving on Mac for .NET Core

### ISSUE THREAD

**Issue by AndrewBrianHall** [xoofx/SharpScss#6]
On the Mac today, libsass.so is being downloaded as the native library dependency.  The SharepScss tries to load the library simply using "libsass" with no extension.  This means that .NET Core looks for libsass.dylib and libsass on the Mac which results in a DllNotFoundException being thrown.

**Comment by xoofx** [comment]
Good catch, never tested it actually on macosx and thought that it was also handled by .NET Core. Will recompile to dylib instead.

**Comment by madskristensen** [comment]
@xoofx , is there anything we can do to help with getting this fixed?

**Comment by xoofx** [comment]
I pushed a 1.3.8 package with the dylib for macosx, let me know if this is working.

I'm unable to test the project, as the native libraries are not well resolved while it seems to work when consuming the NuGet package... looks like a bug in dotnet cli/tests...

**Comment by AndrewBrianHall** [comment]
It's working for me on my Macbook, thanks

**Comment by xoofx** [comment]
Great, thanks for the feedback
