### ISSUE TITLE
[Question] Adding Support for "generally" invalid syntax

### ISSUE THREAD

**Issue by dansiegel** [xoofx/SharpScss#8]
I'm wanting to use SharpScss to compile Scss for Xamarin.Forms. The issue is that css as implemented for Xamarin.Forms introduces `^base` as valid syntax for css. This isn't generally considered valid syntax though and results in an error:

```css
^contentpage {
  margin: 10px;
}
```

```
SharpScss.ScssException : Error: Invalid CSS after "}": expected 1 selector or at-rule, was "^contentpage {"
        on line 7 of Templates/Scss/style2.scss
```

Is there a way that I can add support for this syntax without disabling error detection?

**Comment by xoofx** [comment]
It is not really possible. SharpScss is simply a wrapper of a native library [libsass](https://github.com/sass/libsass) so we don't have any way to change the parsing behavior (unless they introduced something recently I'm not aware of)
